source 'https://rubygems.org'

gem "therubyracer"
gem "less-rails"
gem "twitter-bootstrap-rails"

gem 'underscore-rails'
gem 'font-awesome-rails'

gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pry'

group :development, :test do
  gem 'byebug'
  gem 'jasmine'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
